project:
  type: website

website:
  title: "WILDS"
  navbar:
    logo: favicon.ico
    pinned: true
    foreground: "#1d345c"
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: https://ocdo.fredhutch.org/programs/wildscp.html
        text: Collaborate
      #- learn.qmd
      - help.qmd
      - getinvolved.qmd
    right:
      - href: "https://ocdo.fredhutch.org/"
        text: OCDO
      - href: "https://github.com/getwilds/"
        text: "{{< fa brands github >}}"

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - file: analytics.html
